const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./src/assets/images/item-1.jpeg",
    desc: "Indulge in heavenly Buttermilk Pancakes, a divine blend of fluffiness and rich flavors. Elevate your breakfast experience today!",
  },
  {
    id: 2,
    title: "Wagyu Delight Burger",
    category: "lunch",
    price: 13.99,
    img: "./src/assets/images/item-2.jpeg",
    desc: "Savor the exquisite Wagyu Delight Burger, a gourmet masterpiece. Juicy, tender, and bursting with succulent flavors. Pure luxury on a bun!",
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./src/assets/images/item-3.jpeg",
    desc: "Unleash your taste buds with the epic Godzilla Milkshake. A towering blend of creamy goodness that will leave you craving more. Conquer your dessert desires!",
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./src/assets/images/item-4.jpeg",
    desc: "Start your mornings with the delightful Country Delight breakfast. Rustic flavors, farm-fresh ingredients, and a comforting touch of homestyle goodness.",
  },
  {
    id: 5,
    title: "Alioli Beefegg",
    category: "lunch",
    price: 22.99,
    img: "./src/assets/images/item-5.jpeg",
    desc: "Indulge in the irresistible Alioli Beef n Egg burger. A mouthwatering fusion of juicy beef, creamy alioli, and a perfectly cooked egg. Pure burger bliss!",
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./src/assets/images/item-6.jpeg",
    desc: "Embark on a dreamy journey with the Oreo Dream milkshake. Rich, velvety, and packed with cookie goodness. A milkshake that will make your taste buds dance!",
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./src/assets/images/item-7.jpeg",
    desc: "Experience breakfast bliss with the Bacon Overflow souffle egg sandwich. Fluffy eggs, crispy bacon, and a burst of savory flavors in every bite. Breakfast elevated!",
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./src/assets/images/item-8.jpeg",
    desc: "Indulge in the American Classic: a timeless hamburger paired with golden crispy fries. A mouthwatering combo that captures the essence of culinary nostalgia.",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./src/assets/images/item-9.jpeg",
    desc: "Find comfort in the Quarantine Buddy milkshake, a delicious treat designed to be shared. Sweet moments, double the joy, and a delightful escape together.",
  },
]
export default menu
